### ISSUE TITLE
Pokaż adres MAC zarejestrowanego urządzenia

### ISSUE THREAD

**Issue by kujaw** [hakierspejs/long-season#51]
Jak w temacie - fajnie by było, jakby na liscie urządzeń był widoczny też adres MAC.

**Comment by thinkofher** [comment]
w zasadzie jest to niemożliwe "by design". adresy mac, podobnie jak hasła, są przechowywane w bazie danych w formie hashu, tak, żeby nie można było sobie kojarzyć adresów mac z użytkownikami long-season

Można pomyśleć o opcji edytowania adresów, tzn zamiana na inny adres. Ale wyświetlanie nie wchodzi w grę.

ang: it is impossible "by design". Mac addresses, same as user passwords, are stored in the database in a form of hash, so you can't associate hardware addresses with long-season users.

We can think about possibility to edit mac addresses, by edit I mean: replace with new address. Showing them is not an option.
